//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.admin.Calendar.Outreach {
    
    
    public partial class Details {
        
        /// <summary>
        /// confirmationDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Forms.UserControlConfirmationPage confirmationDelete;
        
        /// <summary>
        /// ucNavCal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Admin.Navigation.Calendar ucNavCal;
        
        /// <summary>
        /// ValidationSummary1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
        
        /// <summary>
        /// acSchoolOrg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Forms.AutoComplete acSchoolOrg;
        
        /// <summary>
        /// acFacilitator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Forms.AutoComplete acFacilitator;
        
        /// <summary>
        /// ddlOffer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlOffer;
        
        /// <summary>
        /// txtPrice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Forms.UserControlTextBox txtPrice;
        
        /// <summary>
        /// txtPupils control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Forms.UserControlTextBox txtPupils;
        
        /// <summary>
        /// txtAdults control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Forms.UserControlTextBox txtAdults;
        
        /// <summary>
        /// txtYearGroup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Forms.UserControlTextBox txtYearGroup;
        
        /// <summary>
        /// txtSpecialNeeds control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Forms.UserControlTextBox txtSpecialNeeds;
        
        /// <summary>
        /// txtSpecialNeedsDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Forms.UserControlTextBox txtSpecialNeedsDetails;
        
        /// <summary>
        /// txtAttendedChildren control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Forms.UserControlTextBox txtAttendedChildren;
        
        /// <summary>
        /// txtAttendedAdults control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Forms.UserControlTextBox txtAttendedAdults;
        
        /// <summary>
        /// txtAttendedTeachers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Forms.UserControlTextBox txtAttendedTeachers;
        
        /// <summary>
        /// chkConfirmationSent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkConfirmationSent;
        
        /// <summary>
        /// txtConfirmationSent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Forms.UserControlDateCalendar txtConfirmationSent;
        
        /// <summary>
        /// txtInitials control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Forms.UserControlTextBox txtInitials;
        
        /// <summary>
        /// txtWorkshopTimes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Forms.UserControlTextEditor txtWorkshopTimes;
        
        /// <summary>
        /// btnSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Forms.UserControlButton btnSubmit;
        
        /// <summary>
        /// btnSubmitChanges control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Forms.UserControlButton btnSubmitChanges;
        
        /// <summary>
        /// ucLogHistory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Admin.SharedObjects.Panel.LogHistory ucLogHistory;
        
        /// <summary>
        /// ucLogNotes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Admin.SharedObjects.Notes.List ucLogNotes;
    }
}
