//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.admin.Organisation.Schools {
    
    
    public partial class List {
        
        /// <summary>
        /// ucNavOrganisation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Admin.Navigation.Organisations ucNavOrganisation;
        
        /// <summary>
        /// acSchool control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Forms.AutoComplete acSchool;
        
        /// <summary>
        /// ucList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Controls.Admin.SharedObjects.List.UtilListView ucList;
    }
}
