<?xml version="1.0" encoding="utf-8"?><Database Name="jupiter_crm" EntityNamespace="Service" ContextNamespace="Service" Class="ServiceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=cfserver;Initial Catalog=jupiter_crm;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="sevenstoriesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Country" Member="Countries">
    <Type Name="Country">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CountryCode" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyCode" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CountryZoneID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CRM_FormFieldItem" Member="CRM_FormFieldItems">
    <Type Name="CRM_FormFieldItem">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CRM_FormFieldID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Label" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="OrderNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsArchived" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CRM_Person" Member="CRM_Persons">
    <Type Name="CRM_Person">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="IsGiftAid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PreviousNames" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsChild" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsConcession" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsCarerMinder" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PrimaryEmail" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="PrimaryTelephone" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CRM_AddressID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsContactEmail" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsContactPost" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeceased" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Reference" Type="System.String" DbType="VarChar(17)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsArchived" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsDoNotMail" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDoNotEmail" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="WebsiteAccountID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CRM_FormFieldAnswer" Member="CRM_FormFieldAnswers" AccessModifier="Internal">
    <Type Name="CRM_FormFieldAnswer" AccessModifier="Internal">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CRM_FormFieldID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TargetReference" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Answer" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CRM_AnnualPassCard" Member="CRM_AnnualPassCards">
    <Type Name="CRM_AnnualPassCard">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MembershipNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CRM_AnnualPassCard_CRM_AnnualPass" Member="CRM_AnnualPasses" ThisKey="ID" OtherKey="CRM_AnnualPassCardID" Type="CRM_AnnualPass" />
    </Type>
  </Table>
  <Table Name="dbo.CRM_AnnualPass" Member="CRM_AnnualPasses">
    <Type Name="CRM_AnnualPass">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CRM_AnnualPassCardID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CRM_AnnualPassTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AmountPaid" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="DiscountApplied" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="PrimaryContactReference" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsPending" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsArchived" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CRM_OfferID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Reference" Type="System.String" DbType="VarChar(21)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PaymentMethod" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="CRM_AnnualPassCard_CRM_AnnualPass" Member="CRM_AnnualPassCard" ThisKey="CRM_AnnualPassCardID" OtherKey="ID" Type="CRM_AnnualPassCard" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CRM_AnnualPassType" Member="CRM_AnnualPassTypes">
    <Type Name="CRM_AnnualPassType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="IsArchived" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DefaultPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="IsWebsite" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsJoint" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CRM_RelationCode" Member="CRM_RelationCodes">
    <Type Name="CRM_RelationCode">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.HoldingPen" Member="HoldingPens">
    <Type Name="HoldingPen">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="DateReceived" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateCommitted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OriginType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="OriginDescription" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="OriginAccountID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Address3" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="County" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Postcode" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CountryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="InterestObjects" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DoNotMail" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DoNotEmail" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AlwaysSendPassInfo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MembershipA" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="MembershipB" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="BasketContents" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="JointHoldingPenID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JointSalutation" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="JointAtoBID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JointBtoAID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JointThisReferenceAB" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CRM_AttendanceEvent" Member="CRM_AttendanceEvents">
    <Type Name="CRM_AttendanceEvent">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="ExternalEventID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CRM_AttendanceEvent_CRM_AttendanceLogGroup" Member="CRM_AttendanceLogGroups" ThisKey="ID" OtherKey="CRM_AttendanceEventID" Type="CRM_AttendanceLogGroup" />
    </Type>
  </Table>
  <Table Name="dbo.CRM_AttendanceLog" Member="CRM_AttendanceLogs">
    <Type Name="CRM_AttendanceLog">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CRM_AttendancePersonTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CRM_CRM_AttendanceLogGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CRM_AttendancePersonType_CRM_AttendanceLog" Member="CRM_AttendancePersonType" ThisKey="CRM_AttendancePersonTypeID" OtherKey="ID" Type="CRM_AttendancePersonType" IsForeignKey="true" />
      <Association Name="CRM_AttendanceLogGroup_CRM_AttendanceLog" Member="CRM_AttendanceLogGroup" ThisKey="CRM_CRM_AttendanceLogGroupID" OtherKey="ID" Type="CRM_AttendanceLogGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CRM_AttendancePersonType" Member="CRM_AttendancePersonTypes">
    <Type Name="CRM_AttendancePersonType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsArchived" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OrderNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CRM_AttendancePersonType_CRM_AttendanceLog" Member="CRM_AttendanceLogs" ThisKey="ID" OtherKey="CRM_AttendancePersonTypeID" Type="CRM_AttendanceLog" />
    </Type>
  </Table>
  <Table Name="dbo.CRM_Calendar" Member="CRM_Calendars">
    <Type Name="CRM_Calendar">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CRM_CalendarTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IsCancelled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CancellationReason" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CancellationAdminID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCancelled" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StartDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByAdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PriceAgreed" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="PriceType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="PrimaryContactReference" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RequiresCatering" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TargetReference" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Reference" Type="System.String" DbType="VarChar(19)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsInvoiced" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceAddressID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InvoiceTitle" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceFirstname" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceLastname" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="DatePaid" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PONumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PrivacyStatus" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ExternalEventID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Limit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Taken" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CRM_CalendarType_CRM_Calendar" Member="CRM_CalendarType" ThisKey="CRM_CalendarTypeID" OtherKey="ID" Type="CRM_CalendarType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CRM_CalendarType" Member="CRM_CalendarTypes">
    <Type Name="CRM_CalendarType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CSSClass" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Hex" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="FixedRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CRM_CalendarType_CRM_Calendar" Member="CRM_Calendars" ThisKey="ID" OtherKey="CRM_CalendarTypeID" Type="CRM_Calendar" />
    </Type>
  </Table>
  <Table Name="dbo.CRM_AttendanceLogGroup" Member="CRM_AttendanceLogGroups">
    <Type Name="CRM_AttendanceLogGroup">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AddedTimeStamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CRM_AttendanceEventID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OriginType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DateInserted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="CRM_AttendanceLogGroup_CRM_AttendanceLog" Member="CRM_AttendanceLogs" ThisKey="ID" OtherKey="CRM_CRM_AttendanceLogGroupID" Type="CRM_AttendanceLog" />
      <Association Name="CRM_AttendanceEvent_CRM_AttendanceLogGroup" Member="CRM_AttendanceEvent" ThisKey="CRM_AttendanceEventID" OtherKey="ID" Type="CRM_AttendanceEvent" IsForeignKey="true" />
    </Type>
  </Table>
</Database>